const liveData = {
  "last_sync": "2026-09-11T20:51:06.163052",
  "sheet_id": "1Gd-M3J_kRd0M6aXBTi4LivVAXWrLMZ9JWluWxkX6Gcg",
  "total_records": 16,
  "records": [
    {
      "Marca temporal": "21/07/2025 14:49:24",
      "Nombre del funcionario solicitante": "Lorena Medel ",
      "Profesión": "Terapeuta ocupacional ",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Roberto fierro 13.***.***-6",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "TO poli mano",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "Lo requiero",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "Lo requiero",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "Lo requiero",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "3",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 1,
      "_ai_agent_analysis": {
        "id": "RP-001",
        "nombreSolicitante": "Lorena Medel",
        "profesionSolicitante": "Terapeuta ocupacional",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
        "unidadTexto": "TO poli mano",
        "usuarioTexto": "Roberto fierro 13381084-6",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador universal con mango",
          "Adaptador corta uñas",
          "Cortador de frutas"
        ],
        "fechaMarca": "21/07/2025 14:49:24",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Roberto F.",
        "nombreUsuarioAnonimizado": "Roberto F.",
        "rutUsuarioNormalizado": "13.***.***-6",
        "rutUsuarioAnonimizado": "13.***.***-6",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Ambulatorio",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Roberto F.) | Contexto: Ambulatorio | Categoría: Ayuda técnica AVD | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 417 días. Asignar moderador urgente.",
        "diasCalculados": 417,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.160977"
      }
    },
    {
      "Marca temporal": "11/03/2026 16:53:51",
      "Nombre del funcionario solicitante": "Natalia Dinamarca Díaz ",
      "Profesión": "Fonoaudióloga",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Andrés Artaza Barrios / 9.***.***-7 / UCI 2 cama 5",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "UCI Adulto sala 2 cama 5",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "Plato adaptado con borde alto. (Foto referencial enviada a Valentina) ",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "13-03-2026",
      "1° IMPLEMENTOS ENTREGADOS": "primera entrega de prueba, no funciona bien ",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 2,
      "_ai_agent_analysis": {
        "id": "RP-002",
        "nombreSolicitante": "Natalia Dinamarca Díaz",
        "profesionSolicitante": "Fonoaudióloga",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
        "unidadTexto": "UCI Adulto sala 2 cama 5",
        "usuarioTexto": "Andrés Artaza Barrios / 9.773.748-7 / UCI 2 cama 5",
        "personalizadaTexto": "Plato adaptado con borde alto. (Foto referencial enviada a Valentina)",
        "piezasDetectadas": [
          "Personalizado: Plato adaptado con borde alto. (Foto referencial enviada a V"
        ],
        "fechaMarca": "11/03/2026 16:53:51",
        "areaSolicitante": "Fonoaudiología",
        "nombreUsuarioNormalizado": "Andrés A.",
        "nombreUsuarioAnonimizado": "Andrés A.",
        "rutUsuarioNormalizado": "9.***.***-7",
        "rutUsuarioAnonimizado": "9.***.***-7",
        "ubicacionNormalizada": "/ UCI 2 cama 5",
        "solicitudPersonalizada": "Plato adaptado con borde alto. (Foto referencial enviada a Valentina)",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Unidad cerrada",
        "categoriaFuncional": "Pieza personalizada",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Alta",
        "motivoPrioridad": "Usuario o unidad crítica en atención cerrada con necesidad funcional urgente.",
        "confianzaPrioridad": 0.95,
        "resumenIA": "Usuario (Andrés A.) | Contexto: Unidad cerrada | Categoría: Pieza personalizada | Prioridad: Alta",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 184 días. Asignar moderador urgente.",
        "diasCalculados": 184,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.161179"
      }
    },
    {
      "Marca temporal": "1/04/2026 8:49:05",
      "Nombre del funcionario solicitante": "jacqueline Fernández Alvarado ",
      "Profesión": "Terapeuta ocpuacional ",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica para UNIDAD de atención ambultatoria (Debe especificar unidad)",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "pedido personal ",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "pedido personal ",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "set de 12 peces de juego tiburon, 4 colores diferentes por favor. Gracias ",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "22-06-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 3,
      "_ai_agent_analysis": {
        "id": "RP-003",
        "nombreSolicitante": "jacqueline Fernández Alvarado",
        "profesionSolicitante": "Terapeuta ocpuacional",
        "destinoTexto": "Implemento/ayuda técnica para UNIDAD de atención ambultatoria (Debe especificar unidad)",
        "unidadTexto": "pedido personal",
        "usuarioTexto": "pedido personal",
        "personalizadaTexto": "set de 12 peces de juego tiburon, 4 colores diferentes por favor. Gracias",
        "piezasDetectadas": [
          "Personalizado: set de 12 peces de juego tiburon, 4 colores diferentes por f"
        ],
        "fechaMarca": "1/04/2026 8:49:05",
        "areaSolicitante": "Otra",
        "nombreUsuarioNormalizado": "Pedido P.",
        "nombreUsuarioAnonimizado": "Pedido P.",
        "rutUsuarioNormalizado": "",
        "rutUsuarioAnonimizado": "",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "set de 12 peces de juego tiburon, 4 colores diferentes por favor. Gracias",
        "destinoTipo": "Unidad",
        "contextoAtencion": "Hospitalizado",
        "categoriaFuncional": "Pieza personalizada",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Unidad (pedido personal) | Contexto: Hospitalizado | Categoría: Pieza personalizada | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 163 días. Asignar moderador urgente.",
        "diasCalculados": 163,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.161318"
      }
    },
    {
      "Marca temporal": "15/05/2026 15:29:37",
      "Nombre del funcionario solicitante": "Alexis silva",
      "Profesión": "Kinesiólogo",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Servicio de urgencias",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Servicio de urgencia",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "Pieza nebulización aerogen x 10",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "22-06-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 4,
      "_ai_agent_analysis": {
        "id": "RP-004",
        "nombreSolicitante": "Alexis silva",
        "profesionSolicitante": "Kinesiólogo",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
        "unidadTexto": "Servicio de urgencia",
        "usuarioTexto": "Servicio de urgencias",
        "personalizadaTexto": "Pieza nebulización aerogen x 10",
        "piezasDetectadas": [
          "Personalizado: Pieza nebulización aerogen x 10"
        ],
        "fechaMarca": "15/05/2026 15:29:37",
        "areaSolicitante": "Kinesiología",
        "nombreUsuarioNormalizado": "Servicio D.",
        "nombreUsuarioAnonimizado": "Servicio D.",
        "rutUsuarioNormalizado": "",
        "rutUsuarioAnonimizado": "",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "Pieza nebulización aerogen x 10",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Hospitalizado",
        "categoriaFuncional": "Pieza personalizada",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Servicio D.) | Contexto: Hospitalizado | Categoría: Pieza personalizada | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 119 días. Asignar moderador urgente.",
        "diasCalculados": 119,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.161445"
      }
    },
    {
      "Marca temporal": "21/07/2026 11:03:04",
      "Nombre del funcionario solicitante": "Valentina Muñoz ",
      "Profesión": "Terapeuta ocupacional ",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Marcela Garrido pinto rut: 13.***.***-9",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Poli to",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "Lo requiero",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "Lo requiero",
      "Adaptador corta uñas   (ayuda técnica)": "Lo requiero",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "Lo requiero",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "Lo requiero",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "30-07-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 5,
      "_ai_agent_analysis": {
        "id": "RP-005",
        "nombreSolicitante": "Valentina Muñoz",
        "profesionSolicitante": "Terapeuta ocupacional",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
        "unidadTexto": "Poli to",
        "usuarioTexto": "Marcela Garrido pinto rut: 13859445-9",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador Universal",
          "Extractor de pastillas",
          "Adaptador corta uñas",
          "Adaptador de llaves",
          "Abridor de latas"
        ],
        "fechaMarca": "21/07/2026 11:03:04",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Marcela G.",
        "nombreUsuarioAnonimizado": "Marcela G.",
        "rutUsuarioNormalizado": "13.***.***-9",
        "rutUsuarioAnonimizado": "13.***.***-9",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Ambulatorio",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Marcela G.) | Contexto: Ambulatorio | Categoría: Ayuda técnica AVD | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 52 días. Asignar moderador urgente.",
        "diasCalculados": 52,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.161582"
      }
    },
    {
      "Marca temporal": "22/07/2026 16:13:47",
      "Nombre del funcionario solicitante": "Valentina Muñoz ",
      "Profesión": "Terapeuta ocupacional ",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Toribio Aravena ",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Poli TO",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "X2",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "Lo requiero",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "Lo requiero",
      "Abotonador  (ayuda técnica)": "Lo requiero",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "Lo requiero",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "22-07-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 6,
      "_ai_agent_analysis": {
        "id": "RP-006",
        "nombreSolicitante": "Valentina Muñoz",
        "profesionSolicitante": "Terapeuta ocupacional",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
        "unidadTexto": "Poli TO",
        "usuarioTexto": "Toribio Aravena",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador Universal (X2)",
          "Extractor de pastillas",
          "Adaptador de llaves",
          "Abotonador",
          "Abridor de latas"
        ],
        "fechaMarca": "22/07/2026 16:13:47",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Toribio A.",
        "nombreUsuarioAnonimizado": "Toribio A.",
        "rutUsuarioNormalizado": "",
        "rutUsuarioAnonimizado": "",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Ambulatorio",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Toribio A.) | Contexto: Ambulatorio | Categoría: Ayuda técnica AVD | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 51 días. Asignar moderador urgente.",
        "diasCalculados": 51,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.161730"
      }
    },
    {
      "Marca temporal": "12/08/2026 12:50:35",
      "Nombre del funcionario solicitante": "Monserrat Viveros ",
      "Profesión": "Kinesiologa",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica para UNIDAD de atención ambultatoria (Debe especificar unidad)",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "servicio de MFYR",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Poli kine/to/fono",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "lo requiero X2",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "13-08-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 7,
      "_ai_agent_analysis": {
        "id": "RP-007",
        "nombreSolicitante": "Monserrat Viveros",
        "profesionSolicitante": "Kinesiologa",
        "destinoTexto": "Implemento/ayuda técnica para UNIDAD de atención ambultatoria (Debe especificar unidad)",
        "unidadTexto": "Poli kine/to/fono",
        "usuarioTexto": "servicio de MFYR",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Hand Grip (X2)"
        ],
        "fechaMarca": "12/08/2026 12:50:35",
        "areaSolicitante": "Kinesiología",
        "nombreUsuarioNormalizado": "Servicio D.",
        "nombreUsuarioAnonimizado": "Servicio D.",
        "rutUsuarioNormalizado": "",
        "rutUsuarioAnonimizado": "",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "",
        "destinoTipo": "Unidad",
        "contextoAtencion": "Ambulatorio",
        "categoriaFuncional": "Stock de unidad",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Stock clínico de rotación habitual para servicio de rehabilitación.",
        "confianzaPrioridad": 0.85,
        "resumenIA": "Unidad (Poli kine/to/fono) | Contexto: Ambulatorio | Categoría: Stock de unidad | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 30 días. Asignar moderador urgente.",
        "diasCalculados": 30,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.161855"
      }
    },
    {
      "Marca temporal": "17/08/2026 14:02:50",
      "Nombre del funcionario solicitante": "Valentina Muñoz ",
      "Profesión": "TO",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Rosa Malverde rut: 11.***.***-6",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Poli TO",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "Lo requiero en tamaño infantil",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "Lo requiero",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "Lo requiero",
      "Abotonador  (ayuda técnica)": "Lo requiero",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "Lo requiero",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "17/08/2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 8,
      "_ai_agent_analysis": {
        "id": "RP-008",
        "nombreSolicitante": "Valentina Muñoz",
        "profesionSolicitante": "TO",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
        "unidadTexto": "Poli TO",
        "usuarioTexto": "Rosa Malverde rut: 11289332-6",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador Universal (Lo requiero en tamaño infantil)",
          "Adaptador corta uñas",
          "Adaptador de llaves",
          "Abotonador",
          "Abridor de latas"
        ],
        "fechaMarca": "17/08/2026 14:02:50",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Rosa M.",
        "nombreUsuarioAnonimizado": "Rosa M.",
        "rutUsuarioNormalizado": "11.***.***-6",
        "rutUsuarioAnonimizado": "11.***.***-6",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Ambulatorio",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Rosa M.) | Contexto: Ambulatorio | Categoría: Ayuda técnica AVD | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 25 días. Asignar moderador urgente.",
        "diasCalculados": 25,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162008"
      }
    },
    {
      "Marca temporal": "18/08/2026 11:23:36",
      "Nombre del funcionario solicitante": "Álvaro Muñoz",
      "Profesión": "Terapia Ocupacional",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Luis Aedo; 6.***.***-1; Medicina sala 21/166; TO",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "Lo requiero en tamaño adulto",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "18/08/2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 9,
      "_ai_agent_analysis": {
        "id": "RP-009",
        "nombreSolicitante": "Álvaro Muñoz",
        "profesionSolicitante": "Terapia Ocupacional",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
        "unidadTexto": "",
        "usuarioTexto": "Luis Aedo; 6264011-1; Medicina sala 21/166; TO",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador Universal (Lo requiero en tamaño adulto)"
        ],
        "fechaMarca": "18/08/2026 11:23:36",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Luis A.",
        "nombreUsuarioAnonimizado": "Luis A.",
        "rutUsuarioNormalizado": "6.***.***-1",
        "rutUsuarioAnonimizado": "6.***.***-1",
        "ubicacionNormalizada": "Medicina sala 21/166; TO",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Hospitalizado",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Alta",
        "motivoPrioridad": "Usuario hospitalizado en sala-cama con requerimiento funcional inmediato para estadía o alta.",
        "confianzaPrioridad": 0.9,
        "resumenIA": "Usuario (Luis A.) | Contexto: Hospitalizado | Categoría: Ayuda técnica AVD | Prioridad: Alta",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 24 días. Asignar moderador urgente.",
        "diasCalculados": 24,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162164"
      }
    },
    {
      "Marca temporal": "31/08/2026 15:08:49",
      "Nombre del funcionario solicitante": "Rosa Contreras ",
      "Profesión": "TO",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica para UNIDAD de atención cerrada (Debe especificar unidad)",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Neurología ",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Neurología ",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "2 TAE 3D",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "31-08-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 10,
      "_ai_agent_analysis": {
        "id": "RP-010",
        "nombreSolicitante": "Rosa Contreras",
        "profesionSolicitante": "TO",
        "destinoTexto": "Implemento/ayuda técnica para UNIDAD de atención cerrada (Debe especificar unidad)",
        "unidadTexto": "Neurología",
        "usuarioTexto": "Neurología",
        "personalizadaTexto": "2 TAE 3D",
        "piezasDetectadas": [
          "Personalizado: 2 TAE 3D"
        ],
        "fechaMarca": "31/08/2026 15:08:49",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Neurología",
        "nombreUsuarioAnonimizado": "Neurología",
        "rutUsuarioNormalizado": "",
        "rutUsuarioAnonimizado": "",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "2 TAE 3D",
        "destinoTipo": "Unidad",
        "contextoAtencion": "Unidad cerrada",
        "categoriaFuncional": "Pieza personalizada",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Alta",
        "motivoPrioridad": "Usuario o unidad crítica en atención cerrada con necesidad funcional urgente.",
        "confianzaPrioridad": 0.95,
        "resumenIA": "Unidad (Neurología) | Contexto: Unidad cerrada | Categoría: Pieza personalizada | Prioridad: Alta",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 11 días. Asignar moderador urgente.",
        "diasCalculados": 11,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162281"
      }
    },
    {
      "Marca temporal": "1/09/2026 10:11:29",
      "Nombre del funcionario solicitante": "Fernanda Orrego",
      "Profesión": "TO",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Patricio De la Fuente, 1.***.***-7, poli TO",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "Lo requiero",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "08-09-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 11,
      "_ai_agent_analysis": {
        "id": "RP-011",
        "nombreSolicitante": "Fernanda Orrego",
        "profesionSolicitante": "TO",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO ambulatorio",
        "unidadTexto": "",
        "usuarioTexto": "Patricio De la Fuente, 10569967, poli TO",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador corta uñas"
        ],
        "fechaMarca": "1/09/2026 10:11:29",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Patricio D.",
        "nombreUsuarioAnonimizado": "Patricio D.",
        "rutUsuarioNormalizado": "1.***.***-7",
        "rutUsuarioAnonimizado": "1.***.***-7",
        "ubicacionNormalizada": "poli TO",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Ambulatorio",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Patricio D.) | Contexto: Ambulatorio | Categoría: Ayuda técnica AVD | Prioridad: Media",
        "alertaSeguimiento": true,
        "accionSugerida": "⚠️ Solicitud sin revisar durante 10 días. Asignar moderador urgente.",
        "diasCalculados": 10,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162405"
      }
    },
    {
      "Marca temporal": "8/09/2026 9:46:35",
      "Nombre del funcionario solicitante": "Valentina Muñoz ",
      "Profesión": "Terapeuta Ocupacional ",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica para UNIDAD de atención ambultatoria (Debe especificar unidad)",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Poli TO",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "Lo requiero en talla S",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "Lo requiero",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "08-09-2026",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 12,
      "_ai_agent_analysis": {
        "id": "RP-012",
        "nombreSolicitante": "Valentina Muñoz",
        "profesionSolicitante": "Terapeuta Ocupacional",
        "destinoTexto": "Implemento/ayuda técnica para UNIDAD de atención ambultatoria (Debe especificar unidad)",
        "unidadTexto": "",
        "usuarioTexto": "Poli TO",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador bolsa de compras (Lo requiero en talla S)",
          "Abridor de latas"
        ],
        "fechaMarca": "8/09/2026 9:46:35",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Poli T.",
        "nombreUsuarioAnonimizado": "Poli T.",
        "rutUsuarioNormalizado": "",
        "rutUsuarioAnonimizado": "",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "",
        "destinoTipo": "Unidad",
        "contextoAtencion": "Hospitalizado",
        "categoriaFuncional": "Stock de unidad",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Stock clínico de rotación habitual para servicio de rehabilitación.",
        "confianzaPrioridad": 0.85,
        "resumenIA": "Unidad (Unidad) | Contexto: Hospitalizado | Categoría: Stock de unidad | Prioridad: Media",
        "alertaSeguimiento": false,
        "accionSugerida": "En flujo normal de producción.",
        "diasCalculados": 3,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162517"
      }
    },
    {
      "Marca temporal": "9/09/2026 12:38:03",
      "Nombre del funcionario solicitante": "Lorena Medel ",
      "Profesión": "To",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Módulo B 62-6",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "Ortesis tae xl bilateral ",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "10-09-2026",
      "1° IMPLEMENTOS ENTREGADOS": "2",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 13,
      "_ai_agent_analysis": {
        "id": "RP-013",
        "nombreSolicitante": "Lorena Medel",
        "profesionSolicitante": "To",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
        "unidadTexto": "",
        "usuarioTexto": "Módulo B 62-6",
        "personalizadaTexto": "Ortesis tae xl bilateral",
        "piezasDetectadas": [
          "Personalizado: Ortesis tae xl bilateral"
        ],
        "fechaMarca": "9/09/2026 12:38:03",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Módulo B.",
        "nombreUsuarioAnonimizado": "Módulo B.",
        "rutUsuarioNormalizado": "",
        "rutUsuarioAnonimizado": "",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "Ortesis tae xl bilateral",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Hospitalizado",
        "categoriaFuncional": "Pieza personalizada",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Módulo B.) | Contexto: Hospitalizado | Categoría: Pieza personalizada | Prioridad: Media",
        "alertaSeguimiento": false,
        "accionSugerida": "En flujo normal de producción.",
        "diasCalculados": 2,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162624"
      }
    },
    {
      "Marca temporal": "9/09/2026 16:26:33",
      "Nombre del funcionario solicitante": "Javier Flores Montiel ",
      "Profesión": "T.O",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Luisa Navarrete, 12.***.***-6",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Uti médica / cama 2",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "Adaptador para vaso, para facilitar AVDB de alimentación, creo que un diámetro de 6 centímetros creo que sería óptimo. Cualquier cosa me preguntan.",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "",
      "1° IMPLEMENTOS ENTREGADOS": "",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 14,
      "_ai_agent_analysis": {
        "id": "RP-014",
        "nombreSolicitante": "Javier Flores Montiel",
        "profesionSolicitante": "T.O",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
        "unidadTexto": "Uti médica / cama 2",
        "usuarioTexto": "Luisa Navarrete, 12320237-6",
        "personalizadaTexto": "Adaptador para vaso, para facilitar AVDB de alimentación, creo que un diámetro de 6 centímetros creo que sería óptimo. Cualquier cosa me preguntan.",
        "piezasDetectadas": [
          "Personalizado: Adaptador para vaso, para facilitar AVDB de alimentación, cr"
        ],
        "fechaMarca": "9/09/2026 16:26:33",
        "areaSolicitante": "Otra",
        "nombreUsuarioNormalizado": "Luisa N.",
        "nombreUsuarioAnonimizado": "Luisa N.",
        "rutUsuarioNormalizado": "12.***.***-6",
        "rutUsuarioAnonimizado": "12.***.***-6",
        "ubicacionNormalizada": "",
        "solicitudPersonalizada": "Adaptador para vaso, para facilitar AVDB de alimentación, creo que un diámetro de 6 centímetros creo que sería óptimo. Cualquier cosa me preguntan.",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Unidad cerrada",
        "categoriaFuncional": "Pieza personalizada",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Alta",
        "motivoPrioridad": "Usuario o unidad crítica en atención cerrada con necesidad funcional urgente.",
        "confianzaPrioridad": 0.95,
        "resumenIA": "Usuario (Luisa N.) | Contexto: Unidad cerrada | Categoría: Pieza personalizada | Prioridad: Alta",
        "alertaSeguimiento": false,
        "accionSugerida": "En flujo normal de producción.",
        "diasCalculados": 2,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162737"
      }
    },
    {
      "Marca temporal": "9/09/2026 16:30:23",
      "Nombre del funcionario solicitante": "Javier Flores Montiel",
      "Profesión": "Terapeuta Ocupacional",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Manuel Rosales Rubio, 9.***.***-7, medicina 24/4, solicitado por TO",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Terapia Ocupacional",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "Lo requiero",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "Lo requiero en tamaño adulto",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "10-09-2026",
      "1° IMPLEMENTOS ENTREGADOS": "2",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 15,
      "_ai_agent_analysis": {
        "id": "RP-015",
        "nombreSolicitante": "Javier Flores Montiel",
        "profesionSolicitante": "Terapeuta Ocupacional",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
        "unidadTexto": "Terapia Ocupacional",
        "usuarioTexto": "Manuel Rosales Rubio, 9441860-7, medicina 24/4, solicitado por TO",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador de lápiz tipo pelota",
          "Adaptador Universal (Lo requiero en tamaño adulto)"
        ],
        "fechaMarca": "9/09/2026 16:30:23",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Manuel R.",
        "nombreUsuarioAnonimizado": "Manuel R.",
        "rutUsuarioNormalizado": "9.***.***-7",
        "rutUsuarioAnonimizado": "9.***.***-7",
        "ubicacionNormalizada": "medicina 24/4, solicitado por TO",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Hospitalizado",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Media",
        "motivoPrioridad": "Usuario ambulatorio en plan de rehabilitación funcional (AVD / apoyo motor).",
        "confianzaPrioridad": 0.88,
        "resumenIA": "Usuario (Manuel R.) | Contexto: Hospitalizado | Categoría: Ayuda técnica AVD | Prioridad: Media",
        "alertaSeguimiento": false,
        "accionSugerida": "En flujo normal de producción.",
        "diasCalculados": 2,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162855"
      }
    },
    {
      "Marca temporal": "9/09/2026 16:36:31",
      "Nombre del funcionario solicitante": "Javier Flores Montiel",
      "Profesión": "Terapeuta Ocupacional",
      "¿A quién va dirigido el producto impreso?": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
      "Si la respuesta anterior fue USUARIO indicar: Nombre, Rut, Servicio(Sala-cama)/Lugar de atención (poli Kine/TO/Fono). ": "Timoteo Carrasco Aedo, 10.***.***-9, UTI médica cama 6",
      "Si la respuesta anterior fue UNIDAD indicar: Unidad y Sala o Poli Kine/TO/Fono ": "Terapeuta Ocupacional",
      "Adaptador de lápiz con mango (ayuda técnica)": "",
      "Adaptador de lápiz tipo pelota  (ayuda técnica)": "Lo requiero",
      "Adaptador de cubiertos con mango  (ayuda técnica)": "",
      "Adaptador Universal  (ayuda técnica)": "",
      "Adaptador universal con mango  (ayuda técnica)": "",
      "Extractor de pastillas   (ayuda técnica)": "",
      "Adaptador corta uñas   (ayuda técnica)": "",
      "Adaptador bolsa de compras  (ayuda técnica)": "",
      "Adaptador de llaves  (ayuda técnica)": "",
      "Abotonador  (ayuda técnica)": "",
      "Cortador de frutas  (ayuda técnica)": "",
      "Abridor de latas (bebidas, atún, jurel, etc)  (ayuda técnica)": "",
      "Masajeador de cicatriz (implemento rh)": "",
      "Hand Grip  (implemento rh)": "",
      "Tablero de motricidad con fósforos   (implemento rh)": "",
      "  Tablero extensor de dedos   (implemento rh)": "",
      "Tablero de monedas  (implemento rh)": "",
      "Jenga de gatitos  (implemento rh)": "",
      "Tazos de discriminación táctil  (implemento rh)": "",
      "Prono-supinador  (implemento rh)": "",
      "Finger Grip  (implemento rh)": "",
      "Encaje de tetris  (implemento rh)": "",
      "Solicitud personalizada: describir brevemente el equipamiento/ayuda técnica solicitada": "",
      "Engranaje para mano  (implemento rh)": "",
      "Vasos con pelotitas de colores  (implemento rh)": "",
      "Enhebradores de animales   (implemento rh)": "",
      "Juego tetris (pequeño)  (implemento rh)": "",
      "Prueba de la Clavija de Nueve Agujeros (9-HPT)  (implemento rh)": "",
      "Soporte de láminas  (ayuda técnica o implemento rh)": "",
      "Ganchos individuales para pared ": "",
      "Gancho triple para pared": "",
      "Encaje de figuras geométricas  (implemento rh)": "",
      "Tablero de monedas ": "",
      "1° FECHA DE ENTREGA": "10-09-2026",
      "1° IMPLEMENTOS ENTREGADOS": "1",
      "2° FECHA DE ENTREGA": "",
      "2° IMPLEMENTOS ENTREGADOS": "",
      "3° FECHA DE ENTREGA": "",
      "3° IMPLEMENTOS ENTREGADOS": "",
      "TOTAL IMPLEMENTOS ENTREGADOS ": "",
      "1° Tiempo de Espera ": "",
      "2° Tiempo de Espera ": "",
      "3° Tiempo de Espera ": "",
      "CATASTRO DE BENEFICIARIOS DIARIOS DE IMPLEMENTOS ADAPTACIONES ": "",
      "_row_index": 16,
      "_ai_agent_analysis": {
        "id": "RP-016",
        "nombreSolicitante": "Javier Flores Montiel",
        "profesionSolicitante": "Terapeuta Ocupacional",
        "destinoTexto": "Implemento/ayuda técnica entregado a USUARIO hospitalizado",
        "unidadTexto": "Terapeuta Ocupacional",
        "usuarioTexto": "Timoteo Carrasco Aedo, 10025261-9, UTI médica cama 6",
        "personalizadaTexto": "",
        "piezasDetectadas": [
          "Adaptador de lápiz tipo pelota"
        ],
        "fechaMarca": "9/09/2026 16:36:31",
        "areaSolicitante": "Terapia Ocupacional",
        "nombreUsuarioNormalizado": "Timoteo C.",
        "nombreUsuarioAnonimizado": "Timoteo C.",
        "rutUsuarioNormalizado": "10.***.***-9",
        "rutUsuarioAnonimizado": "10.***.***-9",
        "ubicacionNormalizada": "UTI médica cama 6",
        "solicitudPersonalizada": "",
        "destinoTipo": "Usuario",
        "contextoAtencion": "Unidad cerrada",
        "categoriaFuncional": "Ayuda técnica AVD",
        "confianzaClasificacion": 0.92,
        "prioridadIA": "Alta",
        "motivoPrioridad": "Usuario o unidad crítica en atención cerrada con necesidad funcional urgente.",
        "confianzaPrioridad": 0.95,
        "resumenIA": "Usuario (Timoteo C.) | Contexto: Unidad cerrada | Categoría: Ayuda técnica AVD | Prioridad: Alta",
        "alertaSeguimiento": false,
        "accionSugerida": "En flujo normal de producción.",
        "diasCalculados": 2,
        "requiereRevisionManual": false,
        "timestampProcesado": "2026-09-11T20:51:06.162967"
      }
    }
  ]
};
